use_esm: false # 在lang emb上加CA，懒得删除了
train_tpse: true
tpse_args: # 应该这样就行
  gst_tokens: 10 # 可以加一些
  gst_heads: 4 # 可以配合tokens数增加而增加，注意要能被hiddensize（256）整除
  gst_gru_layers: 1
  gst_gru_hidden_size: 128
  tpse_fc_layers: 1
  tpse_gru_layers: 1
  tpse_gru_hidden_size: 128

# 为了variance添加的mel相关
mel_base: 'e'
audio_num_mel_bins: 128
fmin: 40
fmax: 16000